version: '3.9'
services:
    redis:
        image: redis
        container_name: redis-1
        restart: always
        ports:
            - 6178:6379
        volumes:
            - redis_data:/data
volumes:
  redis_data:
networks:
  default:
    name: redis-network

