version: '3.8'

services:
  age:
    image: apache/age                       # Use the Apache AGE image
    container_name: age                      # Name of the container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}                  # Set PostgreSQL password
      POSTGRES_DB: data                      # Set default database name
    ports:
      - "5432:5432"                          # Map port 5432 on host to container
    volumes:
      - apache:/var/lib/postgresql/data      # Persist data in a Docker volume

volumes:
  apache:
