version: "3.8"

services:
  mongodb:
    image: mongo:8.0.1
    container_name: mongodb_c1
    ports:
      - "27017:27017"  
    volumes:
      - mongodbvol1:/data/db  
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_1  
      MONGO_INITDB_ROOT_PASSWORD: $user_1_pwd 

volumes:
  mongodbvol1:
