version: "3.8"

services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
      - pgvect:/var/lib/postgresql/data

volumes:
  pgvect:

