version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb:2.17.1-pg15
    container_name: time1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydatabase
    volumes:
      - timescale:/var/lib/postgresql/data
    restart: always

volumes:
  timescale:

